CREATE TABLE param_ejecutivo_cuenta(
   ID  SERIAL PRIMARY KEY,
   NOMBRE           TEXT      NOT NULL,
   CODIGO           TEXT      NOT NULL
);


CREATE TABLE EJECUTIVO_NEGOCIOS(
   ID  SERIAL PRIMARY KEY,
   NOMBRE           TEXT      NOT NULL,
   CODIGO           TEXT      NOT NULL
);

CREATE TABLE TIPO_CLIENTE(
   ID  SERIAL PRIMARY KEY,
   NOMBRE           TEXT      NOT NULL,
);


CREATE TABLE REGIONALES(
   ID  INTEGER PRIMARY KEY,
   NOMBRE           TEXT      NOT NULL
);